Add sync option for max-age of content/assets
Squidex/squidex-samples pull request #73
Opened 2023-08-02 15:56 UTC by nicholasconfer

For apps with large amounts of assets or content, the ability to sync a smaller portion of data will improve overall performance of sync operations, while still syncing required updates.

**Example**
``sq config use app-1``
``sq sync out app-sync-7-days --lookback-days 7``
``sq config use app-2``
``sq sync in app-sync-7-days``

This will give the past 7 days of created/update content and assets.  Other sync items such as schemas, workflows, etc will remain GetAll.

2023-08-02 17:57 UTC, SebastianStehle commented
Hi,

thanks a lot, a few comments:

1. Can we find another name for "lookback"? perhaps maxage? I was reading "loopback" first and I was very confused.
2. Should this parameter also be available for "sync in", so that you can also sync in a part of an export.
3. Potentially this can break your content. Lets say you use references and you have a very old content item that is referenced everywhere, for example something like a currency or country that does not change usually. Can we detect that or document that?

2023-08-02 18:59 UTC, nicholasconfer commented
Thank you for the well-written CLI code, it was very straightforward to work with. Responding to your suggestions:

1. Agreed, I'll change it to "max-age."

2. I initially omitted adding this to the sync in because it would require additional JSON data to the sync out files created and create potential inconsistencies in results to the user if not fully considering their sync out.  For instance if I sync out 1 week, I can't sync in 1 month.  Let me know if you'd like to have this added in, I can create a commit if needed.

3. My thinking may be off here.  I believe if a content item is updated, the reference should remain. Assuming all content was previously synced, the references should be correct even with a short date range. Can you elaborate more on this?  Is there a potential bug I'm missing, or just need to document the feature well so users understand there needs to be a previous full-sync?

One last item that came to my attention reading your third point. I overlooked content/asset deletion. Not sure if this is an issue though, as this might not be captured if someone only performs upserts anyways on a full sync out and in.  Just raising it to your attention in-case I'm mistaken here.

2023-08-03 05:40 UTC, SebastianStehle commented
Thanks for your nice words.

1. Great
2. Good point
3. What is about an initial sync? If you use the sync command to create a dev environment or so?

2023-08-03 13:57 UTC, SebastianStehle commented
Yes, but we can also release this change, if it is helpful for you.

2023-08-03 14:48 UTC, nicholasconfer commented
Your call, I'm able to run this change currently from my branch, so its not too big a deal at the moment.  I'm just preparing for a move over to sync.  Currently we've been doing backup/restore, which is not recommended in your docs and of course not optimal because it recreates and duplicates assets over multiple project ids.

Still have some other problems to work through in terms of moving to sync that are unrelated to this.  Will likely reach out to you separately in near future, just making sure we have our ducks in row first, and working on a couple other projects at same time.

2023-08-03 15:58 UTC, SebastianStehle requested changes

2023-08-03 15:58 UTC, SebastianStehle commented on cli/Squidex.CLI/Squidex.CLI.Core/Commands/Implementation/Sync/Assets/AssetsSynchronizer.cs
> +                if (asset.Created >= options.MaxAgeDate || asset.LastModified >= options.MaxAgeDate)
LastModified should always be the same as created for new assets and contents so the condition can be simplified. I also tend to invert the "if" in this case so reduce nesting.

2023-08-03 15:58 UTC, SebastianStehle commented on cli/Squidex.CLI/Squidex.CLI/Commands/App_Sync.cs
> +                return MaxAge == null ? DateTimeOffset.MinValue : new DateTimeOffset(DateTime.Today.AddDays(-(int)MaxAge));
Is timespan not supported directly? Or another unit like hours? I think it would be useful to sync everything since a short timeframe.

2023-08-03 18:28 UTC, SebastianStehle commented on cli/Squidex.CLI/Squidex.CLI/Commands/App_Sync.cs
> +            [Option("max-age", Description = "Content & assets created or last modified within timeSpan defined")]
"time span" and a dot please ;)

2023-09-11 08:45 UTC, merged